import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner"
import { Inter as FontSans } from "next/font/google"
import { GeistSans } from 'geist/font/sans';
import "./globals.css";
import { SiteHeader } from "@/components/header/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <SiteHeader/>
        {children}
        </body>
        <Toaster />
    </html>
  );
}
